base: &base
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  database: <%= ENV['MYSQL_DATABASE'] %>
  pool: 5
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>

development:
  primary:
    <<: *base

test:
  primary:
    <<: *base
    database: <%= ENV['MYSQL_TEST_DATABASE'] %>

production:
  primary:
    <<: *base
    reconnect: true
